#!/usr/bin/with-contenv bash

# create configuration directory
mkdir -p \
	/config/qBittorrent/config/ \
	/config/openvpn \
	/config/flood \
	/var/run/openvpn \
	/dev/net

# write credentials to file
if [ -n ${OPENVPN_USERNAME} ] && [ -n ${OPENVPN_PASSWORD} ]; then
	printf "${OPENVPN_USERNAME}\n${OPENVPN_PASSWORD}" >/config/openvpn/credentials.txt
elif [ ! -f /config/openvpn/credentials.txt ]; then
	printf "username\npassword" >/config/openvpn/credentials.txt
	echo "OpenVPN username or password was not specified in the 'OPENVPN_USERNAME' or 'OPENVPN_PASSWORD' variables."
	sleep infinity
fi

# set nameserver
echo "nameserver ${DNS}" >/etc/resolv.conf

[[ ! -f /config/qBittorrent/config/qBittorrent.conf ]] &&
	cp /defaults/qBittorrent.conf /config/qBittorrent/config/qBittorrent.conf

# permissions
chown -R abc:abc \
	/config \
	/var/run/openvpn \
	/downloads
chmod -fR a=,ug+rwX \
	/var/run/openvpn || :
